library(corrplot)
library(DescTools)
new_data = read.csv(choose.files())
str(new_data)
colSums(is.na(new_data))
View(new_data)
new_data = na.omit(new_data)
c = cor(new_data)
corrplot(c,method="circle")
library(psych)
KMO(new_data)
cortest.bartlett(new_data)
v=eigen(c)
plot(v$values,type="b")
factanal(new_data,4)
f=factanal(new_data,4,rotation = "varimax")
f
loads<-f$loadings
fa.diagram(loads)
out<-factanal(x=new_data,factors = 4,scores = "regression")
scores = out$scores
dim(scores)
data_frame = cbind(new_data,scores)
dim(data_frame)
View(data_frame)
boxplot(data_frame)
